version: '3.8'

services:
  pps_contenedor_nuevo:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongoimg

  mongoimg:
    image: mongo:latest
    container_name: mongoimg
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
